### ISSUE TITLE
SFML/Audio.hpp: No file or directory

### ISSUE THREAD

**Issue by mateusfg7** [MechaDragonX/TerminalVideo#1]
![image](https://user-images.githubusercontent.com/40613276/113569940-b74b0e00-95e9-11eb-8140-233f384e1607.png)

```
g++ main.cpp -c -o obj/main.o -std=c++17
main.cpp:5:10: fatal error: SFML/Audio.hpp: No file or directory
5 | #include <SFML/Audio.hpp>
  |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:27: obj/main.o] Erro 1
```

**Comment by MechaDragonX** [comment]
You have to install the SFML package. On Debian-based distributions, install `libsfml-dev`. On Arch Linux based distributions, simply install `sfml`.
I've only used Debian, Ubuntu, and Arch, so I don't know what to do on other distros.

I hope that helps!

**Comment by MechaDragonX** [comment]
Once you do so, the output should be:
```sh
g++ main.cpp -c -o obj/main.o -std=c++17
g++ obj/main.o -o bin/termvid -std=c++17  -lsfml-audio -lsfml-system
```
